# Generated by Django 5.2.3 on 2025-06-27 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('import_csv_file', models.FileField(blank=True, null=True, upload_to='leads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(unique=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lead_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.leadlist')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedInAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('connected_via_extension', models.BooleanField(default=False)),
                ('profile_name', models.CharField(max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('track_heyreach_conversations_only', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_follows_limit', models.IntegerField(default=0)),
                ('daily_messages_limit', models.IntegerField(default=0)),
                ('daily_inmail_limit', models.IntegerField(default=0)),
                ('daily_connection_request_limit', models.IntegerField(default=0)),
                ('is_warm', models.BooleanField(default=False)),
                ('sending_days', models.JSONField(default=list)),
                ('sending_start_time', models.TimeField(blank=True, null=True)),
                ('sending_end_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.proxy')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exclusion_lists', models.ManyToManyField(blank=True, related_name='excluded_campaigns', to='tasks.leadlist')),
                ('lead_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.leadlist')),
                ('sending_accounts', models.ManyToManyField(to='tasks.linkedinaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_outbound_message', models.BooleanField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.lead')),
                ('linkedin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.linkedinaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('action_type', models.CharField(choices=[('CONNECTION_REQUEST', 'Connection Request'), ('MESSAGE', 'Message'), ('INMAIL', 'InMail'), ('VIEW_PROFILE', 'View Profile'), ('LIKE_POST', 'Like Post')], max_length=50)),
                ('wait_days', models.IntegerField(default=0)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('subject_line', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_variables', models.JSONField(blank=True, null=True)),
                ('message_variations', models.JSONField(blank=True, null=True)),
                ('fallback_message_content', models.TextField(blank=True, null=True)),
                ('ends_automation_on_response', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.campaign')),
                ('next_step_on_accepted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_step_accepted', to='tasks.sequencestep')),
                ('next_step_on_not_accepted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_step_not_accepted', to='tasks.sequencestep')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_sequence', 'In Sequence'), ('pending', 'Pending'), ('paused', 'Paused'), ('failed', 'Failed'), ('finished', 'Finished'), ('responded', 'Responded')], max_length=50)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('is_responded', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.lead')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.sequencestep')),
            ],
        ),
    ]
